# Generated by Django 4.2.3 on 2023-07-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Wallet',
        ),
    ]
